(custom-set-variables
  ;; custom-set-variables was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(LaTeX-command "latex")
 '(LaTeX-math-abbrev-prefix ";")
 '(LaTeX-version "2e")
 '(TeX-newline-function (quote newline-and-indent))
 '(TeX-region "._region_")
 '(ada-case-attribute (quote ada-loose-case-word))
 '(ada-case-exception-file (quote ("~/.emacs.d/.ada_case_exceptions")))
 '(ada-case-identifier (quote ada-loose-case-word))
 '(ada-clean-buffer-before-saving nil)
 '(ada-label-indent 0)
 '(ada-language-version (quote ada2005))
 '(ada-move-to-declaration t)
 '(ada-search-directories (quote ("." "$ADA_INCLUDE_PATH" "/usr/adainclude" "/usr/local/adainclude" "/opt/gnu/adainclude")))
 '(ada-xref-create-ali nil)
 '(ada-xref-other-buffer t)
 '(ansi-color-for-comint-mode t)
 '(ansi-color-names-vector ["black" "indian red" "palegreen3" "goldenrod" "skyblue3" "medium orchid" "darkSlateGray3" "honeydew2"])
 '(auto-revert-interval 2)
 '(auto-save-list-file-prefix "~/.emacs.d/private/auto-save-list/.saves-")
 '(backup-by-copying t)
 '(backup-directory-alist (quote (("." . "~/.emacs.d/private/.emacs-backups"))))
 '(bsh-startup-timeout nil)
 '(c-basic-offset 4)
 '(calendar-american-date-display-form (quote ((if dayname (concat dayname ", ")) day monthname year)))
 '(calendar-date-display-form (quote ((if dayname (concat dayname ", ")) day " " monthname " " year)))
 '(canlock-password "4ce36c892d2956af4fcae9953f8567309d50e4e0")
 '(color-theme-is-cumulative nil)
 '(color-theme-libraries (quote ("~/.emacs.d/packages/colortheme/themes/color-theme-wombat.el" "~/.emacs.d/packages/colortheme/themes/color-theme-library.el")))
 '(color-theme-load-all-themes nil)
 '(column-number-mode t)
 '(completion-pcm-word-delimiters "-_. ")
 '(delete-old-versions t)
 '(dired-listing-switches "-alh")
 '(ecb-analyse-face (quote speedbar-highlight-face))
 '(ecb-directory-face (quote speedbar-highlight-face))
 '(ecb-history-face (quote speedbar-highlight-face))
 '(ecb-layout-name "left8")
 '(ecb-layout-window-sizes (quote (("left3" (0.12101910828025478 . 0.2765957446808511) (0.12101910828025478 . 0.3404255319148936) (0.12101910828025478 . 0.3617021276595745)) ("left-dir-plus-speedbar" (0.10191082802547771 . 0.4782608695652174) (0.10191082802547771 . 0.5)))))
 '(ecb-method-face (quote speedbar-highlight-face))
 '(ecb-options-version "2.32")
 '(ecb-source-face (quote speedbar-highlight-face))
 '(ecb-tip-of-the-day nil)
 '(ecb-windows-width 0.13)
 '(else-kill-proceed-to-next-placeholder t)
 '(erc-fill-column 72)
 '(erc-nick "joesmoe")
 '(erc-port 8001)
 '(erc-server "irc.freenode.net")
 '(face-font-family-alternatives (quote (("Monospace" "DejaVu Sans Mono" "courier" "fixed") ("courier" "fixed") ("Sans Serif" "helv" "helvetica" "arial" "fixed") ("helv" "helvetica" "arial" "fixed"))))
 '(flymake-gui-warnings-enabled nil)
 '(frame-background-mode (quote dark))
 '(glasses-face (quote bold))
 '(glasses-separator "")
 '(global-font-lock-mode t)
 '(graphviz-dot-auto-indent-on-semi nil)
 '(graphviz-dot-indent-width 3)
 '(hudson-jar-file "/usr/local/lib/java/lib/ext/hudson.jar")
 '(icicle-apropos-cycle-next-keys (quote ([next] [(control n)])))
 '(icicle-apropos-cycle-previous-keys (quote ([prior] [(control p)])))
 '(icicle-reminder-prompt-flag nil)
 '(indent-tabs-mode nil)
 '(inhibit-startup-screen t)
 '(initial-scratch-message "")
 '(jde-checkstyle-classpath (quote ("/usr/share/java/checkstyle.jar" "/usr/share/java/checkstyle-optional.jar")))
 '(jde-compiler (quote (("eclipse java compiler server" "/home/joe/.emacs.d/customizations/ecj.jar"))))
 '(jde-complete-function (quote jde-complete-ido))
 '(jde-ecj-command-line-args (quote ("-d" "none" "-1.5" "-warn:-serial")))
 '(jde-enable-abbrev-mode t)
 '(jde-gen-class-buffer-template (quote ("(funcall jde-gen-boilerplate-function)" "(jde-gen-get-package-statement)" "(progn (require 'jde-javadoc) (jde-javadoc-insert-start-block))" "\" * Describe class \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" "\" here.\" 'n" "\" \" (jde-javadoc-insert-empty-line)" "\" \" (jde-javadoc-insert-empty-line)" "\" \" (jde-gen-save-excursion (jde-javadoc-insert 'tempo-template-jde-javadoc-author-tag))" "\" \" (jde-javadoc-insert-end-block)" "\"public class \"" "(file-name-sans-extension (file-name-nondirectory buffer-file-name))" \.\.\.)))
 '(jde-help-docsets (quote (("JDK API" "/usr/share/doc/sun-java6-jdk/html/api" nil) ("User (javadoc)" "/usr/local/share/doc/java/java3d-1_5-spec") ("User (javadoc)" "/usr/local/share/doc/java/jmf20-apidocs") ("User (javadoc)" "/usr/local/share/doc/java/jogl-1.1.2") ("User (javadoc)" "/usr/local/share/doc/java/jama"))))
 '(jde-help-use-frames nil)
 '(jde-javadoc-author-tag-template "\"* @author:\" user-full-name n>
\"* @author: Adam Royal\"")
 '(jde-jdk (quote ("1.6.0.10")))
 '(jde-jdk-doc-url "/usr/share/doc/sun-java6-jdk/html/api/overview-summary.html")
 '(jde-jdk-registry (quote (("1.6.0.10" . "/usr/lib/jvm/java-6-sun-1.6.0.10"))))
 '(jde-junit-tester-name-tag (cons "Test" "Suffix") t)
 '(jde-plugins-directory "/home/joe/.emacs.d/extras/jde-plugins/")
 '(jde-sourcepath (quote (".")))
 '(kept-new-versions 3)
 '(line-number-mode t)
 '(ls-lisp-dirs-first t)
 '(minibuffer-prompt-properties (quote (read-only t point-entered minibuffer-avoid-prompt face minibuffer-prompt)))
 '(mouse-avoidance-mode (quote banish) nil (avoid))
 '(mumamo-chunk-coloring (quote submode-colored))
 '(nglobal-hl-line-mode t)
 '(nxhtml-skip-welcome t)
 '(org-agenda-custom-commands (quote (("d" todo "DELEGATED" nil) ("c" todo "DONE|DEFERRED|CANCELLED" nil) ("w" todo "WAITING" nil) ("W" agenda "" (\.\.\.)) ("A" agenda "" (\.\.\. \.\.\. \.\.\.)) ("u" alltodo "" (\.\.\. \.\.\.)))))
 '(org-agenda-files (quote ("~/org/todo.org")))
 '(org-agenda-ndays 7)
 '(org-agenda-show-all-dates t)
 '(org-agenda-skip-deadline-if-done t)
 '(org-agenda-skip-scheduled-if-done t)
 '(org-agenda-start-on-weekday nil)
 '(org-deadline-warning-days 14)
 '(org-default-notes-file "~/org/notes.org")
 '(org-fast-tag-selection-single-key (quote expert))
 '(org-insert-labeled-timestamps-at-point t)
 '(org-log-done (quote note))
 '(org-remember-store-without-prompt t)
 '(org-remember-templates (quote ((116 "* TODO %?
  %u" "~/org/todo.org" "Tasks") (110 "* %u %?" "~/org/notes.org" "Notes"))))
 '(org-reverse-note-order t)
 '(preview-icon-specs nil)
 '(ps-font-family (quote Courier))
 '(python-python-command "python2.6")
 '(quack-fontify-style nil)
 '(quack-global-menu-p nil)
 '(quack-pretty-lambda-p t)
 '(quack-smart-open-paren-p t)
 '(recentf-mode t)
 '(recentf-save-file "~/.emacs.d/private/.recentf")
 '(remember-annotation-functions (quote (org-remember-annotation)))
 '(remember-handler-functions (quote (org-remember-handler)))
 '(scroll-bar-mode nil)
 '(scroll-preserve-screen-position 1)
 '(sgml-basic-offset 4)
 '(show-paren-mode t)
 '(show-trailing-whitespace nil)
 '(smex-save-file "~/.emacs.d/private/smex.save")
 '(split-width-threshold 100)
 '(split-window-preferred-function nil)
 '(tags-table-list (quote ("TAGS")))
 '(tool-bar-mode nil)
 '(tooltip-mode nil)
 '(tramp-temp-name-prefix "~/.emacs.d/private/tramp.")
 '(transient-mark-mode t)
 '(version-control t)
 '(w3m-default-save-directory "~/.emacs.d/private/.w3m")
 '(w3m-favicon-size (quote (16 . 16)))
 '(w3m-init-file "~/.emacs.d/private/.emacs-w3m")
 '(w3m-profile-directory "~/.w3m")
 '(w3m-use-cookies t)
 '(w3m-use-tab-menubar nil)
 '(w3m-use-toolbar nil)
 '(winner-mode t nil (winner))
 '(woman-use-own-frame nil)
 '(x-select-enable-clipboard t))
(custom-set-faces
  ;; custom-set-faces was added by Custom.
  ;; If you edit it by hand, you could mess it up, so be careful.
  ;; Your init file should contain only one such instance.
  ;; If there is more than one, they won't work right.
 '(emms-browser-artist-face ((t (:foreground "skyblue3"))))
 '(highlight ((((class color) (min-colors 88) (background dark)) (:background "darkolivegreen"))))
 '(hl-line ((t (:background "#212121"))))
 '(icicle-input-completion-fail-lax ((((background dark)) (:foreground "peru" :underline t :weight bold))))
 '(mumamo-background-chunk-major ((((class color) (min-colors 88) (background dark)) (:background "#242424"))))
 '(mumamo-background-chunk-submode ((((class color) (min-colors 88) (background dark)) (:background "#282828"))))
 '(preview-face ((t (:background "#1d3030"))))
 '(speedbar-highlight-face ((((class color) (background dark)) (:foreground "skyblue3" :underline "skyblue3" :weight bold))))
 '(speedbar-tag-face ((((class color) (background dark)) (:foreground "peru"))))
 '(trailing-whitespace ((((class color) (background dark)) (:underline "red"))))
 '(variable-pitch ((t (:family "Calibri")))))
